all:
	g++ TimeCode.cpp -Wall TimeCodeTests.cpp -o time-code
	g++ TimeCode.cpp -Wall NASALaunchAnalysis.cpp -o nasa
	g++ TimeCode.cpp -Wall PaintDryTimer.cpp -o pdt
	
runtime-code:
	./time-code
	
runnasa:
	./nasa
	
runpdt:
	./pdt
